//木
var Astraea=new Object();
Astraea.id="Astraea";
Astraea.name="义神星";
Astraea.nature="wood";
Astraea.style="S";
Astraea.moc="childs/assets/live2d/Astraea/Astraea/000000.model.json";
Astraea.moc_s="childs/assets/live2d/Astraea/Astraea_s/000000.model.json";
Astraea.moc_o="childs/assets/live2d/Astraea/Astraea_o/000000.model.json";
map.set("Astraea",Astraea);

var Hera=new Object();
Hera.id="Hera";
Hera.name="赫拉";
Hera.nature="wood";
Hera.style="D";
Hera.moc="childs/assets/live2d/Hera/Hera/000000.model.json";
Hera.moc_s="childs/assets/live2d/Hera/Hera_s/000000.model.json";
Hera.moc_o="childs/assets/live2d/Hera/Hera_o/000000.model.json";
Hera.moc_1="childs/assets/live2d/Hera/Hera_1/000000.model.json";
map.set("Hera",Hera);

var Sirens=new Object();
Sirens.id="Sirens";
Sirens.name="塞壬";
Sirens.nature="wood";
Sirens.style="A";
Sirens.moc="childs/assets/live2d/Sirens/Sirens/000000.model.json";
Sirens.moc_s="childs/assets/live2d/Sirens/Sirens_s/000000.model.json";
Sirens.moc_o="childs/assets/live2d/Sirens/Sirens_o/000000.model.json";
map.set("Sirens",Sirens);

var Syrinx=new Object();
Syrinx.id="Syrinx";
Syrinx.name="绪任克斯";
Syrinx.nature="wood";
Syrinx.style="H";
Syrinx.moc="childs/assets/live2d/Syrinx/Syrinx/000000.model.json";
Syrinx.moc_s="childs/assets/live2d/Syrinx/Syrinx_s/000000.model.json";
Syrinx.moc_o="childs/assets/live2d/Syrinx/Syrinx_o/000000.model.json";
map.set("Syrinx",Syrinx); 

var Midas=new Object();
Midas.id="Midas";
Midas.name="迈达斯";
Midas.nature="wood";
Midas.style="J";
Midas.moc="childs/assets/live2d/Midas/Midas/000000.model.json";
Midas.moc_s="childs/assets/live2d/Midas/Midas_s/000000.model.json";
Midas.moc_o="childs/assets/live2d/Midas/Midas_o/000000.model.json";
Midas.moc_1="childs/assets/live2d/Midas/Midas_1/000000.model.json";
map.set("Midas",Midas);

var Epona=new Object();
Epona.id="Epona";
Epona.name="伊波娜";
Epona.nature="wood";
Epona.style="S";
Epona.moc="childs/assets/live2d/Epona/Epona/000000.model.json";
Epona.moc_s="childs/assets/live2d/Epona/Epona_s/000000.model.json";
Epona.moc_o="childs/assets/live2d/Epona/Epona_o/000000.model.json";
map.set("Epona",Epona); 

var Mammon=new Object();
Mammon.id="Mammon";
Mammon.name="玛门";
Mammon.nature="wood";
Mammon.style="D";
Mammon.moc="childs/assets/live2d/Mammon/Mammon/000000.model.json";
Mammon.moc_s="childs/assets/live2d/Mammon/Mammon_s/000000.model.json";
Mammon.moc_o="childs/assets/live2d/Mammon/Mammon_o/000000.model.json";
map.set("Mammon",Mammon);

var Brownies=new Object();
Brownies.id="Brownies";
Brownies.name="布朗尼";
Brownies.nature="wood";
Brownies.style="S";
Brownies.moc="childs/assets/live2d/Brownies/Brownies/000000.model.json";
Brownies.moc_s="childs/assets/live2d/Brownies/Brownies_s/000000.model.json";
Brownies.moc_o="childs/assets/live2d/Brownies/Brownies_o/000000.model.json";
map.set("Brownies",Brownies);

var Cammy=new Object();
Cammy.id="Cammy";
Cammy.name="嘉米";
Cammy.nature="wood";
Cammy.style="J";
Cammy.moc="childs/assets/live2d/Cammy/Cammy/000000.model.json";
Cammy.moc_s="childs/assets/live2d/Cammy/Cammy_s/000000.model.json";
map.set("Cammy",Cammy);

var Clamps=new Object();
Clamps.id="Clamps";
Clamps.name="克兰普斯";
Clamps.nature="wood";
Clamps.style="A";
Clamps.moc="childs/assets/live2d/Clamps/Clamps/000000.model.json";
Clamps.moc_s="childs/assets/live2d/Clamps/Clamps_s/000000.model.json";
Clamps.moc_o="childs/assets/live2d/Clamps/Clamps_o/000000.model.json";
Clamps.moc_1="childs/assets/live2d/Clamps/Clamps_1/000000.model.json";
Clamps.moc_2="childs/assets/live2d/Clamps/Clamps_2/000000.model.json";
Clamps.moc_3="childs/assets/live2d/Clamps/Clamps_3/000000.model.json";
Clamps.moc_4="childs/assets/live2d/Clamps/Clamps_4/000000.model.json";
map.set("Clamps",Clamps);

var Nicole=new Object();
Nicole.id="Nicole";
Nicole.name="妮可";
Nicole.nature="wood";
Nicole.style="A";
Nicole.moc="childs/assets/live2d/Nicole/Nicole/000000.model.json";
Nicole.moc_s="childs/assets/live2d/Nicole/Nicole_s/000000.model.json";
Nicole.moc_o="childs/assets/live2d/Nicole/Nicole_o/000000.model.json";
Nicole.moc_1="childs/assets/live2d/Nicole/Nicole_1/000000.model.json";
Nicole.moc_2="childs/assets/live2d/Nicole/Nicole_2/000000.model.json";
Nicole.moc_w="childs/assets/live2d/Nicole/Nicole_w/000000.model.json";
map.set("Nicole",Nicole);

var Daphneth=new Object();
Daphneth.id="Daphneth";
Daphneth.name="达芙妮丝";
Daphneth.nature="wood";
Daphneth.style="A";
Daphneth.moc="childs/assets/live2d/Daphneth/Daphneth/000000.model.json";
Daphneth.moc_s="childs/assets/live2d/Daphneth/Daphneth_s/000000.model.json";
Daphneth.moc_o="childs/assets/live2d/Daphneth/Daphneth_o/000000.model.json";
Daphneth.moc_w="childs/assets/live2d/Daphneth/Daphneth_w/000000.model.json";
map.set("Daphneth",Daphneth);

var Luynn=new Object();
Luynn.id="Luynn";
Luynn.name="路茵";
Luynn.nature="wood";
Luynn.style="J";
Luynn.moc="childs/assets/live2d/Luynn/Luynn/000000.model.json";
Luynn.moc_s="childs/assets/live2d/Luynn/Luynn_s/000000.model.json";
Luynn.moc_o="childs/assets/live2d/Luynn/Luynn_o/000000.model.json";
map.set("Luynn",Luynn);

var Bartoli=new Object();
Bartoli.id="Bartoli";
Bartoli.name="巴托丽";
Bartoli.nature="wood";
Bartoli.style="S";
Bartoli.moc="childs/assets/live2d/Bartoli/Bartoli/000000.model.json";
Bartoli.moc_s="childs/assets/live2d/Bartoli/Bartoli_s/000000.model.json";
Bartoli.moc_o="childs/assets/live2d/Bartoli/Bartoli_o/000000.model.json";
Bartoli.moc_w="childs/assets/live2d/Bartoli/Bartoli_w/000000.model.json";
map.set("Bartoli",Bartoli);

var Mona=new Object();
Mona.id="Mona";
Mona.name="莫娜";
Mona.nature="wood";
Mona.style="S";
Mona.moc="childs/assets/live2d/Mona/Mona/000000.model.json";
Mona.moc_s="childs/assets/live2d/Mona/Mona_s/000000.model.json";
Mona.moc_1="childs/assets/live2d/Mona/Mona_1/000000.model.json";
Mona.moc_w="childs/assets/live2d/Mona/Mona_w/000000.model.json";
map.set("Mona",Mona);

var Change_wood=new Object();
Change_wood.id="Change_wood";
Change_wood.name="木嫦娥";
Change_wood.nature="wood";
Change_wood.style="A";
Change_wood.moc="childs/assets/live2d/Change_wood/Change_wood/000000.model.json";
Change_wood.moc_s="childs/assets/live2d/Change_wood/Change_wood_s/000000.model.json";
map.set("Change_wood",Change_wood);

var m056=new Object();
m056.id="m056";
m056.name="m056";
m056.nature="wood";
m056.style="A";
m056.moc="childs/assets/live2d/m056/m056_01/000000.model.json";
m056.moc_s="childs/assets/live2d/m056/m056_02/000000.model.json";
m056.moc_o="childs/assets/live2d/m056/m056_00/000000.model.json";
map.set("m056",m056);
